# This is a basic workflow to help you get started with Actions

name: Merge matrix-js-sdk and update clients

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches: [krombel_websockets]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: './repo'
          token: ${{ secrets.GH_PAT }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
      - name: Install yarn
        run: "npm install -g yarn"
          
      - name: Check out repos
        run: |
          git clone --depth=1 https://github.com/vector-im/element-web --single-branch
          git clone --depth=1 https://github.com/ajbura/cinny --single-branch
          
      - name: Build Element
        run: |
          cd ./element-web
          yarn
          yarn build
          cp ../repo/element-config.json ./webapp/config.json
          cd ..

      - name: Build Cinny
        run: |
          cd ./cinny
          yarn
          yarn build
          cp ../repo/cinny-config.json ./dist/config.json
          
      - name: Deploy element.catvibers.me
        uses: crazy-max/ghaction-github-pages@v2
        with:
            target_branch: gh_pages
            build_dir: element-web/webapp
            fqdn: element.catvibers.me
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy cinny.catvibers.me
        uses: crazy-max/ghaction-github-pages@v2
        with:
            target_branch: gh_pages
            repo: aagithubbot/cinny.catvibers.me
            build_dir: cinny/dist
            fqdn: cinny.catvibers.me
        env:
            GITHUB_TOKEN: ${{ secrets.GH_PAT }}
